// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzKJ3fy5af4tBdHo89P7wJHFVxltkg2XQ',
    appId: '1:1099323109524:web:0eca72dbafffe79d60c481',
    messagingSenderId: '1099323109524',
    projectId: 'session-one-fe7c8',
    authDomain: 'session-one-fe7c8.firebaseapp.com',
    storageBucket: 'session-one-fe7c8.appspot.com',
    measurementId: 'G-MTRSB1PN1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6X5a-Rhyxa0VFcLmobFoY_9sxAGqrpxc',
    appId: '1:1099323109524:android:4a87c9fb3289351160c481',
    messagingSenderId: '1099323109524',
    projectId: 'session-one-fe7c8',
    storageBucket: 'session-one-fe7c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKrrE3RkhPzITCd9DuwJTOnByKn4Mnko',
    appId: '1:1099323109524:ios:9cc4c656db8fe0d960c481',
    messagingSenderId: '1099323109524',
    projectId: 'session-one-fe7c8',
    storageBucket: 'session-one-fe7c8.appspot.com',
    iosBundleId: 'skylinecoderz.com.sessionOne',
  );
}
